apiVersion: v1
kind: Service
metadata:
  name: cost-management-app
  labels:
    app.kubernetes.io/name: cost-management-app
    confighub.com/component: cost-management-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cost-management-app
  ports:
    - name: http
      port: 80
      targetPort: http
