apiVersion: v1
kind: Secret
metadata:
  name: beta-dev-use1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    org: beta
    env: dev
    region: use1
    provider: azure
type: Opaque
stringData:
  name: beta-dev-use1
  server: https://beta-dev-use1.k8s.example.invalid
