apiVersion: v1
kind: Secret
metadata:
  name: beta-prod-aps1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    org: beta
    env: prod
    region: aps1
    provider: azure
type: Opaque
stringData:
  name: beta-prod-aps1
  server: https://beta-prod-aps1.k8s.example.invalid
