apiVersion: v1
kind: Secret
metadata:
  name: beta-prod-usw2
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    org: beta
    env: prod
    region: usw2
    provider: aws
type: Opaque
stringData:
  name: beta-prod-usw2
  server: https://beta-prod-usw2.k8s.example.invalid
