apiVersion: v1
kind: Secret
metadata:
  name: gamma-dev-use1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    org: gamma
    env: dev
    region: use1
    provider: azure
type: Opaque
stringData:
  name: gamma-dev-use1
  server: https://gamma-dev-use1.k8s.example.invalid
