apiVersion: v1
kind: Secret
metadata:
  name: gamma-prod-aps1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    org: gamma
    env: prod
    region: aps1
    provider: azure
type: Opaque
stringData:
  name: gamma-prod-aps1
  server: https://gamma-prod-aps1.k8s.example.invalid
