apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-api-config
  namespace: apps
data:
  application.yaml: |
    spring:
      application:
        name: inventory-api
      datasource:
        url: jdbc:postgresql://postgres.platform.svc:5432/inventory
        username: inventory
    inventory:
      environment: dev
    management:
      endpoints:
        web:
          exposure:
            include: health,info
    feature:
      inventory:
        reservationMode: optimistic
  application-stage.yaml: |
    inventory:
      environment: stage
    feature:
      inventory:
        reservationMode: strict
  application-prod.yaml: |
    inventory:
      environment: prod
    server:
      port: 8081
    feature:
      inventory:
        reservationMode: strict
