apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: apptique
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apptique
      component: frontend
  template:
    metadata:
      labels:
        app: apptique
        component: frontend
    spec:
      serviceAccountName: frontend
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 80
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 80
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
