apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apptique-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: apptique
    app.kubernetes.io/instance: apptique-prod
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/confighub/examples.git
    targetRevision: main
    path: incubator/apptique-argo-app-of-apps/manifests/apptique/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: apptique-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
