apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: apptique
    component: frontend
    environment: dev
    app.kubernetes.io/instance: apptique-dev
    argocd.argoproj.io/instance: apptique-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apptique
      component: frontend
  template:
    metadata:
      labels:
        app: apptique
        component: frontend
        environment: dev
    spec:
      serviceAccountName: frontend
      containers:
        - name: server
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 80
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: apptique
    component: frontend
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: apptique
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app: apptique
    component: frontend
    environment: dev
