apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: confighubplaceholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/confighubai/cubbychat/frontend:1.1.7
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: confighubplaceholder
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: confighubplaceholder
spec:
  ingressClassName: nginx
  rules:
  - host: base.local.cubby.bz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
